# Kansas City Housing Prices

In [6]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
# Assign the path to a string variable named data_path
data_path = 'kc_house_data.csv'

housing = pd.read_csv(data_path)

# Print the price column of housing
print(housing.price)

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...   
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64


In [11]:
# Use a numpy array to define price as a 32-bit float
price = np.array(housing['price'], np.float32)

# Define waterfront as a Boolean using cast
waterfront = tf.cast(housing['waterfront'], tf.bool)

# Define an additional feature, size
size = np.array(housing['sqft_living'], np.float32)

# Print price and waterfront
print(price)
print(waterfront)
print(size)

[221900. 538000. 180000. ... 402101. 400000. 325000.]
tf.Tensor([False False False ... False False False], shape=(21613,), dtype=bool)
[1180. 2570.  770. ... 1020. 1600. 1020.]


In [9]:
print(housing.columns)

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')


In [13]:
# Define intercept and slope
intercept = tf.Variable(0.1, np.float32)
slope = tf.Variable(0.1, np.float32)

In [14]:
# Define a linear regression model
def linear_regression(intercept, slope, features = size):
    return intercept + features * slope

In [15]:
# Compute the predicted values and loss
def loss_function(intercept, slope, targets=price, features=size):
    predictions = linear_regression(intercept, slope)
    return tf.keras.losses.mse(targets, predictions)

In [16]:
# Define an optimization operation
opt = tf.keras.optimizers.Adam()

In [22]:
# Minimize the loss function and print the loss
for j in range(1000):
    opt.minimize(lambda: loss_function(intercept, slope), var_list = [intercept, slope])
    print((loss_function(intercept, slope)))

tf.Tensor(423475680000.0, shape=(), dtype=float32)
tf.Tensor(423473000000.0, shape=(), dtype=float32)
tf.Tensor(423470300000.0, shape=(), dtype=float32)
tf.Tensor(423467600000.0, shape=(), dtype=float32)
tf.Tensor(423464900000.0, shape=(), dtype=float32)
tf.Tensor(423462240000.0, shape=(), dtype=float32)
tf.Tensor(423459500000.0, shape=(), dtype=float32)
tf.Tensor(423456800000.0, shape=(), dtype=float32)
tf.Tensor(423454100000.0, shape=(), dtype=float32)
tf.Tensor(423451330000.0, shape=(), dtype=float32)
tf.Tensor(423448700000.0, shape=(), dtype=float32)
tf.Tensor(423445950000.0, shape=(), dtype=float32)
tf.Tensor(423443230000.0, shape=(), dtype=float32)
tf.Tensor(423440550000.0, shape=(), dtype=float32)
tf.Tensor(423437800000.0, shape=(), dtype=float32)
tf.Tensor(423435080000.0, shape=(), dtype=float32)
tf.Tensor(423432450000.0, shape=(), dtype=float32)
tf.Tensor(423429770000.0, shape=(), dtype=float32)
tf.Tensor(423427000000.0, shape=(), dtype=float32)
tf.Tensor(423424360000.0, shape

tf.Tensor(423007880000.0, shape=(), dtype=float32)
tf.Tensor(423005200000.0, shape=(), dtype=float32)
tf.Tensor(423002470000.0, shape=(), dtype=float32)
tf.Tensor(422999720000.0, shape=(), dtype=float32)
tf.Tensor(422997030000.0, shape=(), dtype=float32)
tf.Tensor(422994380000.0, shape=(), dtype=float32)
tf.Tensor(422991600000.0, shape=(), dtype=float32)
tf.Tensor(422988940000.0, shape=(), dtype=float32)
tf.Tensor(422986220000.0, shape=(), dtype=float32)
tf.Tensor(422983600000.0, shape=(), dtype=float32)
tf.Tensor(422980850000.0, shape=(), dtype=float32)
tf.Tensor(422978130000.0, shape=(), dtype=float32)
tf.Tensor(422975370000.0, shape=(), dtype=float32)
tf.Tensor(422972750000.0, shape=(), dtype=float32)
tf.Tensor(422970030000.0, shape=(), dtype=float32)
tf.Tensor(422967350000.0, shape=(), dtype=float32)
tf.Tensor(422964600000.0, shape=(), dtype=float32)
tf.Tensor(422961870000.0, shape=(), dtype=float32)
tf.Tensor(422959200000.0, shape=(), dtype=float32)
tf.Tensor(422956500000.0, shape

tf.Tensor(422551220000.0, shape=(), dtype=float32)
tf.Tensor(422548540000.0, shape=(), dtype=float32)
tf.Tensor(422545850000.0, shape=(), dtype=float32)
tf.Tensor(422543160000.0, shape=(), dtype=float32)
tf.Tensor(422540440000.0, shape=(), dtype=float32)
tf.Tensor(422537760000.0, shape=(), dtype=float32)
tf.Tensor(422535000000.0, shape=(), dtype=float32)
tf.Tensor(422532300000.0, shape=(), dtype=float32)
tf.Tensor(422529660000.0, shape=(), dtype=float32)
tf.Tensor(422526980000.0, shape=(), dtype=float32)
tf.Tensor(422524220000.0, shape=(), dtype=float32)
tf.Tensor(422521500000.0, shape=(), dtype=float32)
tf.Tensor(422518820000.0, shape=(), dtype=float32)
tf.Tensor(422516130000.0, shape=(), dtype=float32)
tf.Tensor(422513440000.0, shape=(), dtype=float32)
tf.Tensor(422510800000.0, shape=(), dtype=float32)
tf.Tensor(422508000000.0, shape=(), dtype=float32)
tf.Tensor(422505300000.0, shape=(), dtype=float32)
tf.Tensor(422502630000.0, shape=(), dtype=float32)
tf.Tensor(422499900000.0, shape

tf.Tensor(422094960000.0, shape=(), dtype=float32)
tf.Tensor(422092370000.0, shape=(), dtype=float32)
tf.Tensor(422089600000.0, shape=(), dtype=float32)
tf.Tensor(422086900000.0, shape=(), dtype=float32)
tf.Tensor(422084120000.0, shape=(), dtype=float32)
tf.Tensor(422081500000.0, shape=(), dtype=float32)
tf.Tensor(422078800000.0, shape=(), dtype=float32)
tf.Tensor(422076100000.0, shape=(), dtype=float32)
tf.Tensor(422073400000.0, shape=(), dtype=float32)
tf.Tensor(422070650000.0, shape=(), dtype=float32)
tf.Tensor(422068030000.0, shape=(), dtype=float32)
tf.Tensor(422065300000.0, shape=(), dtype=float32)
tf.Tensor(422062620000.0, shape=(), dtype=float32)
tf.Tensor(422059870000.0, shape=(), dtype=float32)
tf.Tensor(422057180000.0, shape=(), dtype=float32)
tf.Tensor(422054530000.0, shape=(), dtype=float32)
tf.Tensor(422051840000.0, shape=(), dtype=float32)
tf.Tensor(422049100000.0, shape=(), dtype=float32)
tf.Tensor(422046370000.0, shape=(), dtype=float32)
tf.Tensor(422043680000.0, shape

tf.Tensor(421455760000.0, shape=(), dtype=float32)
tf.Tensor(421453070000.0, shape=(), dtype=float32)
tf.Tensor(421450380000.0, shape=(), dtype=float32)
tf.Tensor(421447730000.0, shape=(), dtype=float32)
tf.Tensor(421444940000.0, shape=(), dtype=float32)
tf.Tensor(421442260000.0, shape=(), dtype=float32)
tf.Tensor(421439570000.0, shape=(), dtype=float32)
tf.Tensor(421436880000.0, shape=(), dtype=float32)
tf.Tensor(421434200000.0, shape=(), dtype=float32)
tf.Tensor(421431500000.0, shape=(), dtype=float32)
tf.Tensor(421428800000.0, shape=(), dtype=float32)
tf.Tensor(421426100000.0, shape=(), dtype=float32)
tf.Tensor(421423400000.0, shape=(), dtype=float32)
tf.Tensor(421420730000.0, shape=(), dtype=float32)
tf.Tensor(421418000000.0, shape=(), dtype=float32)
tf.Tensor(421415320000.0, shape=(), dtype=float32)
tf.Tensor(421412600000.0, shape=(), dtype=float32)
tf.Tensor(421409900000.0, shape=(), dtype=float32)
tf.Tensor(421407260000.0, shape=(), dtype=float32)
tf.Tensor(421404500000.0, shape

tf.Tensor(420968040000.0, shape=(), dtype=float32)
tf.Tensor(420965420000.0, shape=(), dtype=float32)
tf.Tensor(420962730000.0, shape=(), dtype=float32)
tf.Tensor(420959940000.0, shape=(), dtype=float32)
tf.Tensor(420957320000.0, shape=(), dtype=float32)
tf.Tensor(420954640000.0, shape=(), dtype=float32)
tf.Tensor(420951920000.0, shape=(), dtype=float32)
tf.Tensor(420949230000.0, shape=(), dtype=float32)
tf.Tensor(420946540000.0, shape=(), dtype=float32)
tf.Tensor(420943860000.0, shape=(), dtype=float32)
tf.Tensor(420941070000.0, shape=(), dtype=float32)
tf.Tensor(420938380000.0, shape=(), dtype=float32)
tf.Tensor(420935760000.0, shape=(), dtype=float32)
tf.Tensor(420933040000.0, shape=(), dtype=float32)
tf.Tensor(420930400000.0, shape=(), dtype=float32)
tf.Tensor(420927670000.0, shape=(), dtype=float32)
tf.Tensor(420924980000.0, shape=(), dtype=float32)
tf.Tensor(420922260000.0, shape=(), dtype=float32)
tf.Tensor(420919500000.0, shape=(), dtype=float32)
tf.Tensor(420916900000.0, shape

Compute the loss using data from the King County housing dataset. You are given a target, price, which is a tensor of house prices, and predictions, which is a tensor of predicted house prices. You will evaluate the loss function and print out the value of the loss.

In [12]:
# Compute the mean squared error (mse)
#loss = keras.losses.mse(price, predictions)

# Print the mean squared error (mse)
#print(loss.numpy())