# Introduction to TensorFlow in Python
Not long ago, cutting-edge computer vision algorithms couldn’t differentiate between images of cats and dogs. Today, a skilled data scientist equipped with nothing more than a laptop can classify tens of thousands of objects with greater accuracy than the human eye. In this course, you will use TensorFlow 2.6 to develop, train, and make predictions with the models that have powered major advances in recommendation systems, image classification, and FinTech. You will learn both high-level APIs, which will enable you to design and train deep learning models in 15 lines of code, and low-level APIs, which will allow you to move beyond off-the-shelf routines. You will also learn to accurately predict housing prices, credit card borrower defaults, and images of sign language gestures.

**Instructor:** Isaiah Hull, senior economist at Sweden's Central Bank

In [1]:
import tensorflow as tf
from tensorflow import constant, add, ones, matmul, multiply, reduce_sum

# $\star$ Chapter 1: Introduction to TensorFlow
Before you can build advanced models in TensorFlow 2, you will first need to understand the basics. In this chapter, you’ll learn how to define constants and variables, perform tensor addition and multiplication, and compute derivatives. Knowledge of linear algebra will be helpful, but not necessary.

### Constants and variables
* TensorFlow's two basic objects of computation are: **constants** and **variables**

#### What is TensorFlow?
* An open-source library for graph-based numerical computation
    * Developed by the Google Brain Team
* Low- and high-level APIs
    * Addition, multiplication, differentiation
    * Design and train machine learning models
* Important changes in TensorFlow 2.0
    * Eager execution enabled by default
        * Allows users to write simpler and more intuitive code
        * Model building with Keras and Estimators (high-level APIs)
        
#### What is a tensor?
* The TensorFlow documentation describes a **tensor** as "generalization of vectors and matrices to potentially higher dimensions."
* If you're not familiar with linear algebra, think of a tensor as **a collection of numbers, which is arranged into a particular shape**.
    * 0-dimensional: point
    * 1-dimensional: line
    * etc
    
### Defining tensors in TensorFlow
* Each object defined below will be a `tf.Tensor object`

In [3]:
# import tensorflow as tf

# 0D Tensor
d0 = tf.ones((1,))

# 1D Tensor
d1 = tf.ones((2,))

# 2D Tensor
d2 = tf.ones((2, 2))

# 3D Tensor
d3 = tf.ones((2, 2, 2))

If we want to print the array contained in that object, we can apply the `.numpy()` method and pass the resulting object to the print function

In [4]:
# Print the 3D tensor
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


### Defining constants in TensorFlow
* A **constant** the simplest category of tensor
* A constant does not change and cannot be trained
    * Immutable
    * Untrainable
* A constant can have any dimension
* In the code below, we've defined two constants:
    * `a` is a 2x3 tensor of 3s
    * `b` is a 2x2 tensor which is constructed from the 1-dimensional tensor: 1, 2, 3, 4

In [5]:
# from tensorflow import constant

# Define a 2x3 constant
a = constant(3, shape=[2, 3])

# Define a 2x2 constant
b = constant([1, 2, 3, 4], shape=[2, 2])

In [6]:
print(a.numpy())

[[3 3 3]
 [3 3 3]]


In [7]:
print(b.numpy())

[[1 2]
 [3 4]]


* Above we worked exclusively with the constant operation
* However, in some cases, there are more convenient options for defining certain types of special tensors
<img src='data/convenience_functions.png' width="400" height="200" align="center"/>

* Use the `.zeros` or `.ones` operations to generate a tensor of arbitrary (but defined) dimension, that is populated entirely with zeros or ones
* Use the `zeros_like` or `ones_like` operations to populate tensors with zeros and ones, copying the dimensions of some input tensor passed to it.
* Use the `.fill` operation to populate a tensor of arbitrary dimension with the same scalar value in each element

In [8]:
fill_ex = tf.fill([3, 3],7)

In [9]:
print(fill_ex.numpy())

[[7 7 7]
 [7 7 7]
 [7 7 7]]


### Defining and initializing variables
* Unlike a constant, a variable's value can change during computation
* The value of a variable is **shared**, **persistent**, and **modifiable**.
* A variable's **data type and shape are fixed**.

In [10]:
# import tensorflow as tf

# Define a variable
a0 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.float32)
a1 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.int16)

# Define a constant
b = tf.constant(2, tf.float32)

# Compute their product
c0 = tf.multiply(a0, b)
c1 = a0 * b

In [11]:
print(c0.numpy())
print(c1.numpy())

[ 2.  4.  6.  8. 10. 12.]
[ 2.  4.  6.  8. 10. 12.]


* Note that certain TensorFlow operations, such as `tf.multiply` are overloaded, which allows us to use the simpler `a0*b` expression instead.

#### Exercises: Defining data as constants
Throughout this course, we will use `tensorflow` version 2.6.0 and will exclusively import the submodules needed to complete each exercise. This will usually be done for you, but you will do it in this exercise by importing `constant` from `tensorflow`.

After you have imported `constant`, you will use it to transform a `numpy` array, `credit_numpy`, into a `tensorflow` constant, `credit_constant`. This array contains feature columns from a dataset on credit card holders and is previewed in the image below. We will return to this dataset in later chapters.

Note that `tensorflow` 2 allows you to use data as either a `numpy` array or a `tensorflow` `constant` object. Using a constant will ensure that any operations performed with that object are done in `tensorflow`.

```
# Import constant from TensorFlow
from tensorflow import constant

# Convert the credit_numpy array into a tensorflow constant
credit_constant = constant(credit_numpy)

# Print constant datatype
print('\n The datatype is:', credit_constant.dtype)

# Print constant shape
print('\n The shape is:', credit_constant.shape)
```

#### Exercises: Defining variables
Unlike a constant, a variable's value can be modified. This will be useful when we want to train a model by updating its parameters.

Let's try defining and printing a variable. We'll then convert the variable to a `numpy` array, print again, and check for differences. Note that `Variable()`, which is used to create a variable tensor, has been imported from `tensorflow` and is available to use in the exercise.

```
# Define the 1-dimensional variable A1
A1 = Variable([1, 2, 3, 4])

# Print the variable A1
print('\n A1: ', A1)

# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print('\n B1: ', B1)
```

### Basic operations
* TensorFlow has a model of computation that revolves around the use of graphs
* A TensorFlow graph contains edges and nodes, where the edges are tensors and the nodes are operations

<img src='data/tf_operation_flow.png' width="400" height="200" align="center"/>

### Applying the addition operator
* We first import the constant and add operations so that we may now define 0-, 1-, and 2-dimensional tensors. 

In [12]:
# Import constant and add from tensorflow
# from tensorflow import constant, add

# Define 0-dimensional tensors
A0 = constant([1])
B0 = constant([2])

# Define 1-dimensional tensors
A1 = constant([1, 2])
B1 = constant([3, 4])

# Define 2-dimensional tensors
A2 = constant([[1, 2], [3, 4]])
B2 = constant([[5, 6], [7, 8]])

### Applying the addition operator
* Finally, let's add them together using the operation for tensor addition
* Note that we can perform scalar addition with `A0` and `B0`, vector addition with `A1` and `B1`, and matrix addition with `A2` and `B2`
* The `add()` operation performs **element-wise addition** with two tensors
* **Element-wise addition requires that both tensors have the same shape:**
    * Scalar addition: 1 + 2 = 3
    * Vector addition: [1, 2] + [3, 4] = [4, 6]
    * Matrix addition:

```
A = [[1, 2],
     [3, 4]]
B = [[5, 6], 
     [7, 8]]
A + B = [[6, 8],
         [10,12]]
```
* Furthermore, the `add()` operator is **overloaded**
    * We can also perform addition using the plus symbol

In [13]:
# Perform tensor addition with add()
C0 = add(A0, B0)
C1 = add(A1, B1)
C2 = add(A2, B2)

In [14]:
print(C0.numpy())
print(C1.numpy())
print(C2.numpy())

[3]
[4 6]
[[ 6  8]
 [10 12]]


### How to perform multiplication in TensorFlow
* We will consider both element-wise and matrix multiplication
* **Element-wise multiplication** performed using the `multiply()` operation
    * Tensors involved **must have the same shape**
* **Matrix multiplication** performed with `matmul()` operator 
    * The `matmul(A, B)` operation multiplies `A` by `B`
    * **Note** that number of columns of `A` must equal the number of rows of `B`
    
#### Applying the multiplication operators

In [15]:
# Import operators from tensorflow
# from tensorflow import ones, matmul, multiply

# Define tensors
A0 = ones(1)
A31 = ones([3, 1])
A34 = ones([3, 4])
A43 = ones([4, 3])

* What types of operations are valid on these tensors of ones?
    * We can perform element-wise multiplication of any element by itself
        * `multiply(A0, A0)`, `multiply(A31, A31)`, and `multiply(A34, A34)`
    * We can perform matrix multiplication on `matmul(A43, A34)`
        * but **not** matmul(A43, A43)
        
### Summing over tensor dimensions
* The `reduce_sum()` operator sums over the dimensions of a tensor
* This can be used to sum over all dimensions of a tensor or just one.
* The `reduce_sum()` operator sums over th dimensions of a tensor
    * `reduce_sum(A)` sums over all dimensions of A
    * `reduce_sum(A, i)` sums over dimension i 

In [16]:
# Import operations from tensorflow
# from tensorflow import ones, reduce_sum

# Define a 2x3x4 tensor of ones
F = ones([2, 3, 4])

* If we sum over all elements of A, we get 24, since the tensor contains 24 elements, all of which are 1 

In [17]:
# Sum over all dimensions
D = reduce_sum(F)

# Sum over dimensions 0, 1, and 2
D0 = reduce_sum(F, 0)
D1 = reduce_sum(F, 1)
D2 = reduce_sum(F, 2)

* If we sum over dimension 0, we get a 3 x 4 matrix of 2s
* If we sum over 1, we get a 2 by 4 matrix of 3s
* If we sum over 2, we get a 2 x3 matrix of 4s
* In each case, we reduce the size of the tensor by summing over one of its dimensions

In [18]:
print(D)

tf.Tensor(24.0, shape=(), dtype=float32)


In [19]:
print(D0)

tf.Tensor(
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]], shape=(3, 4), dtype=float32)


In [20]:
print(D1)

tf.Tensor(
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]], shape=(2, 4), dtype=float32)


In [21]:
print(D2)

tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]], shape=(2, 3), dtype=float32)
